# Site settings
name: Kiran Boke
description: "Technology Analyst - Credit Suisse"
sub-description: "Java | C# | Full Stack Developer"
url: ""


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  KBOKE1
pluralsight_username: kiranboke 
hackerrank_username: kiran_boke1
facebook_username: kiran.boke.5
linkedin_username: kiran-boke
resume_url: https://drive.google.com/file/d/1ChCGFUU_xuJKi_jv-4NTfqXbkioIfuLh/view?usp=sharing
instagram_username:  kiran_boke
stack_of_username: 15708760/kiran-boke
email: kiran.boke1@gmail.com


avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "imgs/kiran.jpg"


front_img: yes
front_img_path: "imgs/background1.jpg"
#front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
